language: c

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gfortran
      - libopenblas-dev
      - libopenmpi-dev

script:
  - make -j DFLAGS="-D__MPI_VERSION=3 -D__parallel -D__HAS_NO_SHARED_GLIBC -D__STATM_TOTAL" LIBS="-llapack -lblas" all
